### ISSUE TITLE
Exception: Underflow in restoreToCount

### ISSUE THREAD

**Issue by kmfish** [ctiao/DanmakuFlameMaster#77]
FATAL EXCEPTION: DFM Cache-Building Thread
    java.lang.IllegalArgumentException: Underflow in restoreToCount
            at android.graphics.Canvas.restoreToCount(Native Method)
            at android.view.TextureView.unlockCanvasAndPost(TextureView.java:687)
            at master.flame.danmaku.ui.widget.DanmakuTextureView.clear(DanmakuTextureView.java:458)
            at master.flame.danmaku.controller.DrawHandler.initRenderingConfigs(DrawHandler.java:437)
            at master.flame.danmaku.controller.DrawHandler.access$1200(DrawHandler.java:39)
            at master.flame.danmaku.controller.DrawHandler$2.ready(DrawHandler.java:455)
            at master.flame.danmaku.controller.CacheManagingDrawTask$CacheManager$CacheHandler.handleMessage(CacheManagingDrawTask.java:427)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:153)
            at android.os.HandlerThread.run(HandlerThread.java:60)

这个异常出现次数还是蛮多的，希望能fix

**Comment by ctiao** [comment]
推荐使用最新代码的DanmakuView代替DanmakuSurfceView和DanmakuTextureView

**Comment by ctiao** [comment]
DanmakuView可以应用View的硬件加速绘制,绘制效率最高，并且系统和布局的兼容度比其他两个更好。
