### ISSUE TITLE
在使用DanmakuView控件时ANR异常

### ISSUE THREAD

**Issue by hllai** [ctiao/DanmakuFlameMaster#81]
"main" prio=5 tid=1 TIMED_WAIT
  | group="main" sCount=1 dsCount=0 obj=0x41caf9a0 self=0x4000b010
  | sysTid=13422 nice=0 sched=0/0 cgrp=apps handle=1075807196
  | state=S schedstat=( 8501538752 1262374500 11577 ) utm=743 stm=107 core=2
  at java.lang.Object.wait(Native Method)
  - waiting on <0x42a82cd8> (a java.lang.Object)
  at java.lang.Object.wait(Object.java:401)
  at master.flame.danmaku.ui.widget.DanmakuView.lockCanvas(DanmakuView.java:231)
  at master.flame.danmaku.ui.widget.DanmakuView.lockCanvasAndClear(DanmakuView.java:246)
  at master.flame.danmaku.ui.widget.DanmakuView.clear(DanmakuView.java:408)
  at com.eebbk.videocomponent.danmaku.DanmakuControl.clearDanmaku(DanmakuControl.java:260)
  at com.eebbk.videocomponent.danmaku.DanmakuControl.seektoDanmaku(DanmakuControl.java:276)
  at com.eebbk.videocomponent.core.VideoPlayerControl.seekDanmaku(VideoPlayerControl.java:4005)
  at com.eebbk.videocomponent.core.VideoPlayerControl$36.onSeekDanmaku(VideoPlayerControl.java:4138)
  at com.eebbk.videocomponent.core.VideoPlayer.seekTo(VideoPlayer.java:643)
  at com.eebbk.videocomponent.core.VideoPlayerControl$8.onStopTrackingTouch(VideoPlayerControl.java:2165)
  at android.widget.SeekBar.onStopTrackingTouch(SeekBar.java:119)
  at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:397)
  at android.view.View.dispatchTouchEvent(View.java:7249)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2177)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1920)
  at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1956)
  at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1405)
  at android.app.Activity.dispatchTouchEvent(Activity.java:2409)
  at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1904)
  at android.view.View.dispatchPointerEvent(View.java:7429)
  at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3353)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3298)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4439)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4418)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4510)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
  at android.os.MessageQueue.nativePollOnce(Native Method)
  at android.os.MessageQueue.next(MessageQueue.java:125)
  at android.os.Looper.loop(Looper.java:124)
  at android.app.ActivityThread.main(ActivityThread.java:5041)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:511)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
  at dalvik.system.NativeStart.main(Native Method)

**Comment by hllai** [comment]
只要使用到了mDanmakuView.clear();就会有这个问题。

**Comment by ctiao** [comment]
确实有这问题 因为在外部主线程调用Danmaku.clear 会进入线程wait ,导致这个问题，@xqq 可以在clear方法里检查下是否主线程

**Comment by xqq** [comment]
修复中。
另：seek时无需手动clear()，DFM seek时会自动清的

**Comment by aheadlcx** [comment]
@xqq  DFM seek 的时候，有没有办法，不会清弹幕
